spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/recipes
    username: user
    password: geronimo
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  flyway:
    enabled: true
    schemas: recipes
    locations: classpath:db
