spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:recipes;INIT=CREATE SCHEMA IF NOT EXISTS recipes;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  h2:
    console:
      enabled: true