spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/recipes
    username: user
    password: geronimo
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: false